return {
    "nvim-treesitter/nvim-treesitter",
    lazy=false,
    build = ":TSUpdate",
    opts = {
        highlight = {
            enable = true,
            disable = {
                enable = true,
                "latex",
            },
        },
        ensure_installed = {
            "bash",
            "c",
            "cpp",
            "c_sharp",
            "css",
            "heex",
            "html",
            "javascript",
            "lua",
            "make",
            "markdown",
            "matlab",
            "powershell",
            "python",
            "query",
            "rust",
            "sql",
            "ssh_config",
            "vim",
            "vimdoc",
        },

        sync_install = false,
        auto_install = true,
        indent = { enable = true },
    },
}
