# Alacritty Configuration

[terminal]
shell = "/bin/bash"

# window
[window]
decorations = "None"
opacity = 0.9
blur = true

[window.dimensions]
columns = 100
lines = 30

# scrollback
[scrolling]
history = 4000
multiplier = 5

# font
[font]
size = 12

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

# clipboard
[selection]
save_to_clipboard = true

# colorscheme
[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
